########################## frontend globlayos ################
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-fe-globalyapp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Installing main backend first
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background   
spec:
  project: default
  sources:
  - repoURL: https://github.com/Globaly-Inc/gitops-globalyapp-deployments.git
    targetRevision: "live-values"
    ref: values   
  - repoURL: "https://github.com/GlobalyHub/GH-infra-and-k8s-charts-central.git"
    path: "helm-charts/self-managed/frontend"  # Fixed: was kube-prometheus-stack
    targetRevision: "infra"  # Latest chart version
    helm:
      valueFiles:
        - $values/gitops-values/production/apps/globalyapp-fe.yml     
  destination:
    server: https://kubernetes.default.svc
    namespace: production-globalyapp-web-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true       
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: -1            # ← unlimited retries
      backoff:
        duration: 60s      # ← base interval of 30 seconds
        factor: 2
        maxDuration: 10m   # ← raised ceiling to accommodate longer backoff chain  