apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: alloy-extra-configs
    namespace: monitoring-agent
    options:
      disableNameSuffixHash: true
    files:
      - agentcis-v2.alloy
      - agentcisapp-queue-consumer.alloy
      - agentcisapp-superadmin.alloy
      - agentcisapp-web-server.alloy
      - microservice-agent-portal.alloy
      - microservice-authentication.alloy
      - microservice-data-import.alloy
      - microservice-email-summary.alloy
      - microservice-onboarding.alloy
      - microservice-report-scheduler.alloy
      - microservice-sms-campaign.alloy
      - microservice-sub-agent-portal.alloy    
      - z-dynamic-label-php-web-agentcis.alloy 
      - z-dynamic-label-php-queue-consumer.alloy 